[package]
name = "speed"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "^1", features = [
    "io-util", "macros", "net", "rt", "sync", "time"
] }
tracing = "^0.1"
tracing-subscriber = { version = "^0.3", features = ["env-filter"] }
