[package]
name = "lrcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "^1.10"
tokio = { version = "^1", features = ["io-util", "macros", "net", "rt", "sync"] }